# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: voicemail-changer

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  secrets: ${file(secrets.json)}
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 60 # The default is 6
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret}
  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to our DynamoDB table.
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - "arn:aws:dynamodb:*:*:table/VoicemailChangerDataTable"
        - "arn:aws:dynamodb:*:*:table/VoicemailChangerUserTable"
    - Effect: Allow
      Action: # Gives permission to publish messages.
        - SNS:Publish
      Resource: "*"
    - Effect: Allow
      Action: # Gives permission to generate audio.
        - polly:SynthesizeSpeech
      Resource: "*"
    - Effect: Allow
      Action: # Gives permission to write logs.
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action: # Gives access to our s3 bucket.
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        - "arn:aws:s3:::voicemail-changer-bucket"
        - "arn:aws:s3:::voicemail-changer-bucket/*"

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  login:
    handler: src/handlers/login.default
    events:
      - http:
          path: sessions
          method: post
          cors: true
  register:
    handler: src/handlers/register.default
    events:
      - http:
          path: register
          method: post
          cors: true
  authorize:
    handler: src/handlers/authorize.default
  submit:
    handler: src/handlers/submit.default
    events:
      - http:
          path: submit
          method: post
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 0
  list:
    handler: src/handlers/list.default
    events:
      - http:
          path: list
          method: get
          cors: true
          authorizer:
            name: authorize
            resultTtlInSeconds: 0
  generate:
    handler: src/handlers/generate.default
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          enabled: true
          arn:
            Fn::GetAtt:
              - VoicemailChangerDataTable
              - StreamArn

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
  Resources:
    VoicemailChangerUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VoicemailChangerUserTable
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    VoicemailChangerDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VoicemailChangerDataTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    VoicemailChangerS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: voicemail-changer-bucket
